name: multi-job

on:
  workflow_dispatch: {}

jobs:
  job-a:
    runs-on: ubuntu-latest
    steps:
    - run: exit 1
  job-a2:
    needs: job-a
    runs-on: ubuntu-latest
    steps:
    - run: exit 1
  job-always:
    needs: [job-a, job-a2]
    runs-on: ubuntu-latest
    if: ${{ always }}
    steps:
    - run: echo always
  job-succes:
    needs: [job-a, job-a2]
    runs-on: ubuntu-latest
    if: ${{ success }}
    steps:
    - run: echo success
  job-failure:
    needs: [job-a, job-a2]
    runs-on: ubuntu-latest
    if: ${{ failure }}
    steps:
    - name: b
      run: echo failure
